title: RK
author: Rafał Karoń
description: My portfolio
keywords: HTML, CSS, Python, Technical Writing, Techwriting, Technical Communication, Techcom, Information Development, Frontend, Backend, Scripts, Automation
since: 2020
logo: "RK"