---
title: About me
description: Key information about me.
avatar: "media/home/me-bw.PNG"
---

## Content developer

Throughout my IT career, I have embraced various roles, with the primary focus on content creation, manipulation, organization, migration, generation, and automation.

My profession is known by many titles, including technical writer, technical documentation specialist, information developer, or content developer. Given the diverse range of my responsibilities and expertise, I believe *content developer* best captures the essence of my work.

### Key tools and technologies

Professionally, I have mainly utilized **oXygen XML Editor** integrated with web-based **Composite Content Management Systems (CCMSs)** that support **DITA XML**. Additionally, I have extensive experience with the industry-standard **DITA XML**, **oXygen XML Editor**, and **GitHub Desktop** stack. I am also familiar with the **RST** format and have worked with **Author-it**. For internal documentation, I have mainly used **Confluence** and **Markdown** in various **README** files.

In my personal projects, I rely on **Visual Studio Code**, **GitHub**, and **Markdown**. I generate content with [Hugo](https://gohugo.io) and publish it using [GitHub Pages](https://pages.github.com/) and [GitHub Actions](https://github.com/features/actions). Previously, I have utilized [Jekyll](https://jekyllrb.com/) for static sites generation.

## Coder

I am a self-taught coder. Currently, I develop my side projects independently and collaborate with software developers at work. My IDE of choice is **Visual Studio Code**, though I can switch to **Vim** and quit it if needed.

I won't lie—I prompt AI for inspiration from time to time. I have found it extremely helpful for composing shell scripts that run in my homelab and for GitHub Actions.

### Technologies

I am keen on finding ways to automate, optimize, and generate reports to save my coworkers from opening terminals or doing repetitive work.

Python
: I am a self-taught Python coder. I use Python in my side projects and to develop internal tools at work. To make coding easier, I've implemented **mypy**, **Ruff**, and **Black** into my workflow. I also use Python for automation in GitHub Actions.
{.text_small}

MicroPython
: I run MicroPython on **Raspberry Pi[^1] Pico** boards. The code interacts with databases and APIs, reads sensor data, and manipulates output devices.
{.text_small}

[^1]: {{% reuse "_reuse/copyr_rpi.md" %}}

Databases
: I use **InfluxDB** to gather data from sensors and APIs in my homelab. For some side projects, I use **MongoDB**.

Bash
: I use Bash scripts to automate repetitive tasks on my macOS and Linux machines. Shell scripts are also very handy for automation in GitHub Actions.
{.text_small}

Apart from the backend activities, I also enjoy styling and templating websites and other outputs.

HTML
: I am proficient in using semantic HTML5 and I advocate structured content.
{.text_small}

CSS
: I am skilled in developing CSS for different viewports, including responsive websites, web apps, and printed media.  
I am also familiar with **LESS** and **SCSS**.
{.text_small}

JavaScript
: I use JavaScript to implement basic functionalities into websites and create simple web apps. Additionally, I have been developing **React** frontends with the assistance of **GitHub Copilot**.
{.text_small}

XML
: I am a **DITA XML** expert familiar with both **technical content** and **learning and training** specializations. I use **XPath** to run complex queries.
{.text_small}

### Content generators

As a content developer specializing in DITA XML, I prioritize separating content from styling for semantic clarity.

DITA Open Toolkit
: My limited **XSL** knowledge enables me to develop simple [DITA-OT](https://www.dita-ot.org/) customizations.

Prince XML
: I have extensive experience in styling PDF templates with HTML, CSS, a touch of XSLT, and the [Prince XML](https://www.princexml.com/) converter. To reduce the code maintenance time, I always make my templates modular, customizable, and extensible.
{.text_small}

Hugo
: I am experienced in designing, developing, and styling Hugo sites. I developed this site from scratch in Hugo. I leverage the **Liquid** template language to keep the template logic modular.
{.text_small}

Jekyll
: I have considerable experience in designing, developing, and styling Jekyll sites. My legacy website used Jekyll under the hood.
{.text_small}

Gatsby
: I have some experience in customizing sites generated by using Gatsby with LESS, TypeScript, and Material Design in mind.
{.text_small}

Docusaurus
: I am experienced in styling Docusaurus sites, extending Docusaurus sites functionalities, and modifying their behavior.
{.text_small}

MkDocs
: I use MkDocs for some of my Python side projects.
{.text_small}

Sphinx
: I have some experience in customizing Sphinx output.
{.text_small}

### Platforms

On a daily basis, I run **macOS**. Professionally, I have been using **Windows** machines.  
To stay in the Linux loop, I  run **Ubuntu** (formerly **Fedora**) on my vintage MacBook Air and **Debian** on my **Raspberry Pi[^1] 4B**.

## Agile leader

While I advocate for Agile methodologies like Scrum and Kanban, I tailor approaches to fit content development contexts, emphasizing clear backlogs, filters, and burndown charts. I favor Jira for task management and view Confluence as a valuable knowledge base supplement.

### Methodology

Scrum was designed as a work framework with an emphasis on software development teams. While it is possible to treat [docs as code](https://www.writethedocs.org/guide/docs-as-code/), content development and software development are still significantly different processes. This difference is particularly prominent if content creators are not regular members of software development teams.

I consider the [Scrum Guide](https://www.Scrumguides.org/index.html) a great basis for building an Agile framework in any development team. However, I often take the liberty of proposing, test-driving, and implementing various alterations to the approach suggested in the guide. If the docs tend to be developed on an ad hoc basis, I am not afraid to gravitate towards the Kanban framework.

### Tools

As a person who always has a clean desk, I enjoy well-curated backlogs, clearly defined items, flawless filters, and model burndown charts.

My weapon of choice is **Jira**; however, I am open to any alternative WMS solutions. For some teams, I find **Confluence** a good and well-integrated addition to Jira, serving as an internal knowledge base.

I am an ardent supporter of keeping everything related to work management in a single place. In the long run, an avalanche of shared sheets is not a maintainable approach.

## Tester

I approach software documentation with a keen eye for usability issues, frequently identifying bugs and UI inconsistencies. My technical writing background enables precise bug logging and acceptance criteria definition.

## Teacher

Once a teacher, always a teacher.

With a master's degree in teaching English, I excel in onboarding, workshops, and communicating with stakeholders, demonstrating software effectively and acting as a consultant.

## After hours

I am passionate about cutting-edge technologies and intrigued by creative business models. I appreciate art and design in various forms. In my leisure time, I engage in individual sports and read books that broaden my worldview. As a minimalist, I thrive in a clean and organized environment for work and relaxation. Privacy is important to me, which is why I maintain a low profile on social media.

### Technology

I believe every content developer in the IT sector should be a tech geek. Documenting what interests you is far more engaging. I enjoy discussing and ranting about tech trends and modern business models.

Here are some resources that keep me informed about the latest in tech:

Podcasts

* [Talk Python To Me](https://talkpython.fm/)
* [Python Bytes Podcast](https://pythonbytes.fm/)
* [TechWriter.koduje()](https://techwriterkoduje.pl/)
* [Na Podsłuchu](https://niebezpiecznik.pl/podcast/)
{.items}

Newsletters

* [unknow.news](https://unknow.news/)
* [Various RSS feeds in NetNewsWire](https://github.com/Ranchero-Software/NetNewsWire)
{.items}

Blogs

* [Niebezpiecznik](https://niebezpiecznik.pl/)
* [It's FOSS](https://itsfoss.com/)
* [OMG! Ubuntu](https://www.omgubuntu.co.uk/)
* [OMG! Linux](https://www.omglinux.com/)
* [Pi My Life Up!](https://pimylifeup.com/)
* [RaspberryTips](https://raspberrytips.com/)
* [The MagPi magazine](https://magpi.raspberrypi.com/articles)
* [Jeff Geerling's Blog](https://www.jeffgeerling.com/blog)
{.items}

YouTube channels

* [TechLinked](https://www.youtube.com/@techlinked)
* [The Linux Experiment](https://www.youtube.com/@TheLinuxEXP)
* [Fireship](https://www.youtube.com/@Fireship)
* [iFixit](https://www.youtube.com/@iFixitYourself)
{.items}

I also enjoy hardware repair and upgrades using my [iFixit](https://ifixit.com) kit and a Leatherman multitool. I strongly support the [Right to repair](https://www.ifixit.com/Right-to-Repair/Intro) movement.

### Photography

While smartphones are capable of stunning photos, I still enjoy using my Canon DSLR and manually developing RAW photos in Affinity Photo.

I shoot various types of photos, from portraits and macros to abstracts. For more of my photography, visit my [Unsplash profile](https://unsplash.com/@rafalkaron).

![A photo of Kona](/media/home/kona2.jpg)
![A photo of Kona](/media/home/kona.jpg)
{.two_column}

### Hiking

Mountain hiking is refreshing and complements my passion for photography. Conveniently, there are plenty of beautiful mountains to explore and photograph in my area.

![A photo from Ciemniak](/media/home/ciemniak.jpg)
![Bieszczady](/media/home/bieszczady.jpg)
{.two_column}

### Cycling

I developed a love for cycling by spending time in a local bicycle shop during my childhood. I can assemble and fix bikes. My road bicycle sees the most use, but I also enjoy riding an old-school mountain bike.

![Bike photo](/media/home/bicycle1.jpg)
![Bike photo](/media/home/bicycle2.jpg)
{.two_column}

### Running

I usually run on my own or with my friend, but I broke my routine by participating in [Business Run 2018](https://live.sts-timing.pl/businessrun2018/person.php?n=63&d=1) as one of the **Motorola Solutions Gatekeepers** runners.

!["Business Run 2018" medal](/media/home/business_run.jpg)
{.huge .center}

### Origami

Paper folding is both intricate and relaxing. Origami figurines make fantastic gifts and minimalistic home or office decor.

![Origami owl](/media/home/origami_snail.jpg)
![Origami fish](/media/home/origami_fish.jpg)
{.two_column}
